### ISSUE TITLE
cbba-problem

### ISSUE THREAD

**Issue by code-xiaobai** [zehuilu/CBBA-Python#2]
Hello, I haven't solved a problem in researching the task allocation of cbba recently. If the agent needs to form a combination to complete the task together, what adjustments should be made in conflict resolution and package building? Thank you very much！

**Comment by zehuilu** [comment]
Hi, I believe the CBBA algorithm and/or its variants can handle the task with cooperation among multiple agents. I'm not sure whether the current algorithm here can handle that. I will check that probably by the end of November since I'm busy these days.

**Comment by code-xiaobai** [comment]
Thank you very much for replying to me in spite of your busy schedule. You said that it could be solved. Maybe I didn't find a suitable solution.

**Comment by zehuilu** [comment]
If one cannot find an existing algorithm that exactly solves this problem, then this could be a perfect research gap that you can jump in and contribute to. Good luck!
