### ISSUE TITLE
Do you know the performance impact (PI) algorithm?

### ISSUE THREAD

**Issue by liaki-001** [zehuilu/CBBA-Python#4]
Hi, the latest distributed task allocation algorithm based on market auction mechanism is performance impact (PI) algorithm, this algorithm is also improved in the framework of CBBA, do you have relevant knowledge about PI algorithm?

**Comment by zehuilu** [comment]
Hi, thanks for reaching out. I'm not aware of this algorithm since distributed task allocation is not in my research scope.
